security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: /
        success_handler: App\Security\LoginSuccessHandler

      logout:
        path: app_logout


  access_control:
    - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_PHARMACIST, ROLE_SELLER ] }
    - { path: ^/pharmacist, roles: ROLE_PHARMACIST }
    - { path: ^/seller/dashboard, roles: ROLE_SELLER }



when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
